# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Custom parts:

# Header
language: r
sudo: false
dist: trusty
cache: packages
latex: false
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

#env
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"

#services
services:
  - xvfb